### ISSUE TITLE
Create walk through for projector

### ISSUE THREAD

**Issue by cassininazir** [artscilab/equipment#1]
@amb141330, will assign to you once you join this repo. 

From *very* beginning setup: 

1 What is the code to get into the touchscreen system (don't want to write here for public to see!)
2. Walk through how to change  projector input
3 Troubleshooting -- who to call when things don't work.

This should be a document that is printed and easily located in the lab.

**Comment by amb141330** [comment]
This document is almost finished. Waiting on the audio equipment set up to be finished before I publish the document. I don't want people having to manually switch the RCA inputs by the console.

**Comment by amb141330** [comment]
No updates here, still waiting on RCA inputs.

**Comment by amb141330** [comment]
Follow at issue #2 for walk through.
