### ISSUE TITLE
set up three ring binder with printed versions of all equipment instructions

### ISSUE THREAD

**Issue by rmalina** [artscilab/equipment#10]
ashton
please can you get together with brian merlo and develop a three ring binder
with printed instructions for use of all equipment in the lab, passwords etc

roger
@cassininazir

**Comment by amb141330** [comment]
This has been done. Will meet with Sandy sometime soon to discuss the ArtSciLab layout.

**Comment by rmalina** [comment]
please send an email to everyone who uses the lab to explain
it and ask them to red line on the instructions any problems they have

make sure you give a file to sandy -i dont think brian made two copies

roger

On Mon, Feb 22, 2016 at 10:58 AM, amb141330 <notifications@github.com>
wrote:

> This has been done. Will meet with Sandy sometime soon to discuss the
> ArtSciLab layout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artscilab/equipment/issues/10#issuecomment-187266390>.
>



-- 
Roger F Malina
is in  Dallas
510-853-2007
