### ISSUE TITLE
Check to see if Firefox is up-to-date on Mac connected to projector

### ISSUE THREAD

**Issue by cassininazir** [artscilab/equipment#2]
I am henceforth calling this Mac **Marconi**. @amb141330, work with Brian on this.

**Comment by rmalina** [comment]
ashton
actually it would be helfpul to have a list of what is installed on any
computer in the lab
and make sure all the software is updated/latest versions
roger/

On Tue, Sep 1, 2015 at 9:49 PM, Cassini Nazir <notifications@github.com>
wrote:

> I am henceforth calling this Mac *Marconi*. @amb141330
> <https://github.com/amb141330>, work with Brian on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artscilab/equipment/issues/2>.
>



-- 
Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
So I updated firefox, but I will have to go through and check other applications for updates.

**Comment by amb141330** [comment]
Walkthrough pretty much done just waiting on some changed in the audio set up from Brian before I make the document public. I don't want people having to switch the audio inputs manually with the RCA cables by the console.

**Comment by amb141330** [comment]
This walk through will be finalized after the completion of the audio booth.

**Comment by amb141330** [comment]
Walkthroughs are being edited on multiple parts of the lab. Still waiting on furniture before we start building the audio booth.

**Comment by amb141330** [comment]
I need to print out the ZOOM recorder walkthrough after going through it with the sound team today.

**Comment by amb141330** [comment]
This has to do with the sheets in the three ring binder. Closing this issue.
