### ISSUE TITLE
admin privileges

### ISSUE THREAD

**Issue by rmalina** [artscilab/equipment#3]
ashton
i think you, cassini and i need admin priviles for the lab computers ?

on the computer that you lent to thulasi for the oculus project-she needs admin
privileges to install some software -she should also have admin privileges

can you submit this to atecsupport as a request and then work with brian
to do that on all the lab computers

roger

**Comment by rmalina** [comment]
here is the tech support email address ATEC Support <ATECSupport@utdallas.edu>

roger

**Comment by amb141330** [comment]
Sent an email requesting administrative privileges. CC'd both @rmalina and @cassininazir

**Comment by amb141330** [comment]
Brian has shared with us the administrative account details for the ArtSciLab computers. Check your email, I will not put that info in this github item.
