### ISSUE TITLE
Audio Equipment Setup

### ISSUE THREAD

**Issue by amb141330** [artscilab/equipment#7]
I've asked Brian to supply us with another audio cable so we do not need to switch inputs between the laptop HDMI and the Mac inside the desk. Will keep this updated.

**Comment by amb141330** [comment]
Nothing changed on the inputs as of yet. Will contact Brian again to check on the status.

**Comment by amb141330** [comment]
Sent Brian another email about this.

**Comment by amb141330** [comment]
This should change when we set up the other audio booth.

**Comment by rmalina** [comment]
ashton=not sure why you are closing this- we just orderd the furniture etc to re organise the lab and set up the recording equipment- have you talked to coordinate the set up with brian ? its not done yet so you shouldnt close this action roger
